# Generated by Django 3.0.5 on 2020-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cases', models.IntegerField()),
                ('dies', models.IntegerField()),
            ],
        ),
    ]
